platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!

def shared_pods

    pod 'ReachabilitySwift', '4.1.0'
    pod 'Alamofire', '4.9.1'
    pod 'ObjectMapper', '3.5.3'
    pod 'SwiftyJSON', '4.0.0'
    pod 'Kingfisher', '4.6.3'
    pod 'GoogleMLKit/TextRecognition'
    # UI stuff
    pod 'MBProgressHUD', '1.1.0'
    
    
    pod 'TimelineTableViewCell', '~> 2.2.1'
end

target 'HealthHack' do
    shared_pods
end


post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
              config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
              config.build_settings['CODE_SIGN_STYLE'] = ""
            end
        end
end
